### ISSUE TITLE
Application start fails if the Email add-on is used and no file storage is registered

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-email#44]
Jmix version: 1.1.0-SNAPSHOT

**Steps to reproduce:**
1. Create a project with dependency on the Email add-on and without dependency on any file storage add-on (localfs or awsfs)
2. Run the app
**AR:** App start fails, an exception is thrown:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'email_EmailCleaner': Injection of autowired dependencies failed; nested exception is java.lang.IllegalStateException: No FileStorage beans registered
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657) ~[spring-beans-5.3.8.jar:5.3.8]
	... 34 common frames omitted
Caused by: java.lang.IllegalStateException: No FileStorage beans registered
	at io.jmix.core.impl.FileStorageLocatorImpl.getDefault(FileStorageLocatorImpl.java:85) ~[jmix-core-1.1.0-SNAPSHOT.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'email_EmailCleaner': Injection of autowired dependencies failed; nested exception is java.lang.IllegalStateException: No FileStorage beans registered

	at io.jmix.email.impl.EmailCleanerImpl.setFileStorage(EmailCleanerImpl.java:57) ~[jmix-email-1.1.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_265]

```
**ER:** The app starts successfully

**Comment by reznikova21** [comment]
Jmix version: 1.1.0-SNAPSHOT
